export enum UpgradeNames {
  COMPOSTING_DRUMS = 'COMPOSTING_DRUMS',
  CHAINSAWS = 'CHAINSAWS',
  TUYERES = 'TUYERES',
  HEAT_RECLAMATORS = 'HEAT_RECLAMATORS',
  PREFABRICATION = 'PREFABRICATION',
  CRATES = 'CRATES',
}
