export enum TechNames {
  BIOMASS_COMPRESSION = 'BIOMASS_COMPRESSION',
  FARMING = 'FARMING',
  SHELTER = 'SHELTER',
  CRYONICS = 'CRYONICS',
  AGROFORESTRY = 'AGROFORESTRY',
  STORAGE = 'STORAGE',
  BIOMASS_RECLAMATION = 'BIOMASS_RECLAMATION',
  EXCAVATION = 'EXCAVATION',
  METALLURGY = 'METALLURGY',
  COMBUSTION_GENERATION = 'COMBUSTION_GENERATION',
}
