export enum TechNames {
  BIOMASS_COMPRESSION = 'BIOMASS_COMPRESSION',
  FARMING = 'FARMING',
  SHELTER = 'SHELTER',
  CRYONICS = 'CRYONICS',
  AGROFORESTRY = 'AGROFORESTRY',
  STORAGE = 'STORAGE',
  EXCAVATION = 'EXCAVATION',
  METALLURGY = 'METALLURGY',
  ELECTROMAGNETISM = 'ELECTROMAGNETISM',
  SUBSURFACE_EXCAVATION = 'SUBSURFACE_EXCAVATION',
}
